import { NextResponse } from "next/server";
import connectDB from "@/lib/mongodb";
import Shelter from "@/models/Shelter";
import Pet from "@/models/Pet";

const sheltersData = [
  {
    name: "Friendicoes SECA",
    city: "New Delhi",
    state: "Delhi",
    address: "271-275, Jangpura, Bhogal, New Delhi, Delhi 110014",
    phone: "+91-11-2431-5480",
    email: "friendicoes@gmail.com",
    website: "https://friendicoes.org",
    description: "One of India's oldest and most respected animal welfare organizations, rescuing and rehabilitating animals since 1979.",
    rating: 4.8,
    totalAdoptions: 1250,
    isVerified: true,
    operatingHours: "9:00 AM - 6:00 PM",
  },
  {
    name: "Blue Cross of India",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "1A, Velachery Main Road, Guindy, Chennai, Tamil Nadu 600032",
    phone: "+91-44-2234-1399",
    email: "info@bluecrossofindia.org",
    website: "https://bluecrossofindia.org",
    description: "A premier animal welfare organization in South India providing shelter, medical care, and adoption services since 1959.",
    rating: 4.9,
    totalAdoptions: 2100,
    isVerified: true,
    operatingHours: "8:30 AM - 5:30 PM",
  },
  {
    name: "CUPA (Compassion Unlimited Plus Action)",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Veterinary College Campus, Hebbal, Bengaluru, Karnataka 560024",
    phone: "+91-80-2351-4541",
    email: "cupabangalore@gmail.com",
    website: "https://cupabangalore.org",
    description: "Bengaluru's leading animal rescue and adoption center, providing comprehensive care for abandoned and injured animals.",
    rating: 4.7,
    totalAdoptions: 980,
    isVerified: true,
    operatingHours: "9:00 AM - 5:00 PM",
  },
  {
    name: "The Welfare of Stray Dogs (WSD)",
    city: "Mumbai",
    state: "Maharashtra",
    address: "Mahalaxmi, Mumbai, Maharashtra 400034",
    phone: "+91-22-2353-7311",
    email: "info@wsdindia.org",
    website: "https://wsdindia.org",
    description: "Mumbai's trusted organization for stray dog welfare, sterilization drives, and pet adoptions since 1985.",
    rating: 4.6,
    totalAdoptions: 1800,
    isVerified: true,
    operatingHours: "10:00 AM - 6:00 PM",
  },
  {
    name: "People For Animals (PFA)",
    city: "Ahmedabad",
    state: "Gujarat",
    address: "Satellite Road, Ahmedabad, Gujarat 380015",
    phone: "+91-79-2692-1714",
    email: "pfa.ahmedabad@gmail.com",
    website: "https://peopleforanimalsindia.org",
    description: "Founded by Maneka Gandhi, PFA Ahmedabad is dedicated to animal rescue, rehabilitation, and finding loving homes.",
    rating: 4.5,
    totalAdoptions: 750,
    isVerified: true,
    operatingHours: "9:30 AM - 5:30 PM",
  },
  {
    name: "SPCA Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    address: "Jawahar Circle, Malviya Nagar, Jaipur, Rajasthan 302017",
    phone: "+91-141-252-0840",
    email: "spcajaipur@gmail.com",
    website: "https://spcajaipur.org",
    description: "Rajasthan's premier animal shelter providing rescue, treatment, and adoption services for all kinds of animals.",
    rating: 4.4,
    totalAdoptions: 620,
    isVerified: true,
    operatingHours: "9:00 AM - 5:00 PM",
  },
  {
    name: "Animal Aid Unlimited",
    city: "Udaipur",
    state: "Rajasthan",
    address: "Badi Village, Near Eklingji, Udaipur, Rajasthan 313001",
    phone: "+91-294-258-3382",
    email: "info@animalaidunlimited.org",
    website: "https://animalaidunlimited.org",
    description: "A world-renowned rescue center in Udaipur treating thousands of injured street animals and facilitating adoptions.",
    rating: 4.9,
    totalAdoptions: 1500,
    isVerified: true,
    operatingHours: "8:00 AM - 6:00 PM",
  },
  {
    name: "Charlie's Animal Rescue Centre (CARE)",
    city: "Hyderabad",
    state: "Telangana",
    address: "Kompally, Secunderabad, Telangana 500100",
    phone: "+91-40-2714-4155",
    email: "care.hyderabad@gmail.com",
    website: "https://careforanimals.in",
    description: "Hyderabad's beloved animal rescue center providing shelter, medical care, and adoption for dogs, cats, and other animals.",
    rating: 4.7,
    totalAdoptions: 890,
    isVerified: true,
    operatingHours: "9:00 AM - 5:30 PM",
  },
  {
    name: "IDA India (In Defense of Animals)",
    city: "Pune",
    state: "Maharashtra",
    address: "Katraj, Pune, Maharashtra 411046",
    phone: "+91-20-2436-0100",
    email: "ida.pune@gmail.com",
    website: "https://idaindia.org",
    description: "A leading animal welfare organization in Pune running rescue operations, veterinary hospital, and adoption programs.",
    rating: 4.6,
    totalAdoptions: 720,
    isVerified: true,
    operatingHours: "9:00 AM - 6:00 PM",
  },
  {
    name: "Sanjay Gandhi Animal Care Centre",
    city: "New Delhi",
    state: "Delhi",
    address: "Raja Garden, New Delhi, Delhi 110015",
    phone: "+91-11-2515-0689",
    email: "sgacc.delhi@gmail.com",
    website: "https://sgacc.org.in",
    description: "One of Asia's largest animal shelters, caring for thousands of animals and running active adoption drives in Delhi.",
    rating: 4.5,
    totalAdoptions: 2500,
    isVerified: true,
    operatingHours: "8:00 AM - 7:00 PM",
  },
  {
    name: "Karuna Animal Shelter",
    city: "Kolkata",
    state: "West Bengal",
    address: "Salt Lake, Sector V, Kolkata, West Bengal 700091",
    phone: "+91-33-2357-8900",
    email: "karuna.kolkata@gmail.com",
    website: "https://karunashelter.org",
    description: "Kolkata's compassionate animal shelter providing rescue, rehabilitation, and forever homes for abandoned pets.",
    rating: 4.3,
    totalAdoptions: 540,
    isVerified: true,
    operatingHours: "9:30 AM - 5:00 PM",
  },
  {
    name: "Peepal Farm",
    city: "Dharamshala",
    state: "Himachal Pradesh",
    address: "Tanda, Dharamshala, Himachal Pradesh 176215",
    phone: "+91-98160-12345",
    email: "hello@peepalfarm.org",
    website: "https://peepalfarm.org",
    description: "A unique farm-based animal sanctuary in the Himalayas rescuing injured animals and promoting sustainable living.",
    rating: 4.8,
    totalAdoptions: 380,
    isVerified: true,
    operatingHours: "8:00 AM - 5:00 PM",
  },
  {
    name: "VOSD (Voice of Stray Dogs)",
    city: "Pune",
    state: "Maharashtra",
    address: "Maval, Pune, Maharashtra 410506",
    phone: "+91-20-6900-1234",
    email: "info@vosd.in",
    website: "https://vosd.in",
    description: "India's largest no-kill dog sanctuary with over 900 dogs, providing lifetime care and facilitating adoptions nationwide.",
    rating: 4.7,
    totalAdoptions: 650,
    isVerified: true,
    operatingHours: "9:00 AM - 5:00 PM",
  },
  {
    name: "Jeev Ashram",
    city: "Lucknow",
    state: "Uttar Pradesh",
    address: "Gomti Nagar, Lucknow, Uttar Pradesh 226010",
    phone: "+91-522-272-1234",
    email: "jeevashram@gmail.com",
    description: "A compassionate animal shelter in Lucknow dedicated to rescuing and rehoming abandoned pets across UP.",
    rating: 4.2,
    totalAdoptions: 420,
    isVerified: true,
    operatingHours: "9:00 AM - 5:30 PM",
  },
  {
    name: "Humane Animal Society (HAS)",
    city: "Coimbatore",
    state: "Tamil Nadu",
    address: "Peelamedu, Coimbatore, Tamil Nadu 641004",
    phone: "+91-422-254-5678",
    email: "has.coimbatore@gmail.com",
    description: "South India's growing animal welfare center providing rescue, veterinary care, and adoption services in Coimbatore.",
    rating: 4.4,
    totalAdoptions: 310,
    isVerified: true,
    operatingHours: "9:00 AM - 5:00 PM",
  },
];

const petsData = [
  {
    name: "Raja",
    type: "Dog",
    breed: "Labrador Retriever",
    age: "2 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/fa147b42-d724-47d2-b21c-53e5a25a72fd.png",
    personality: ["Friendly", "Playful", "Good with kids"],
    description: "Raja is a lovable golden Labrador who adores playing fetch and cuddling. He's great with children and other pets. Fully vaccinated and ready for his forever home!",
    weight: "28 kg",
    color: "Golden",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 2500,
    shelterIndex: 0,
  },
  {
    name: "Sheru",
    type: "Dog",
    breed: "Indian Spitz",
    age: "1.5 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/a53c8729-52fc-4238-8863-18e501727256.png",
    personality: ["Alert", "Loyal", "Energetic"],
    description: "Sheru is a beautiful white Indian Spitz with a fluffy coat. He's very alert, loves morning walks, and is incredibly loyal to his family.",
    weight: "8 kg",
    color: "White",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 1500,
    shelterIndex: 3,
  },
  {
    name: "Tiger",
    type: "Dog",
    breed: "German Shepherd",
    age: "3 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/d47e9508-14d1-43de-a5c2-8ceffdd630b5.png",
    personality: ["Intelligent", "Protective", "Trainable"],
    description: "Tiger is a well-trained German Shepherd who is both protective and gentle. He responds to basic commands and loves outdoor activities.",
    weight: "35 kg",
    color: "Black & Tan",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 3000,
    shelterIndex: 2,
  },
  {
    name: "Brownie",
    type: "Dog",
    breed: "Indian Pariah (Indie)",
    age: "1 year",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/adbf4b3c-5fd6-4940-b944-59e9f05cd5d3.png",
    personality: ["Gentle", "Adaptable", "Street Smart"],
    description: "Brownie is a rescued Indie dog with a beautiful brown coat. She's incredibly adaptable, healthy, and has the sweetest temperament.",
    weight: "15 kg",
    color: "Brown",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 1000,
    shelterIndex: 6,
  },
  {
    name: "Coco",
    type: "Dog",
    breed: "Beagle",
    age: "8 months",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/8843a4a0-3a4b-4374-8f78-2e1a4b98dc2e.png",
    personality: ["Curious", "Playful", "Vocal"],
    description: "Coco is an adorable Beagle puppy with the cutest floppy ears. He loves sniffing around, playing with toys, and is very food-motivated!",
    weight: "9 kg",
    color: "Tricolor",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 3500,
    shelterIndex: 7,
  },
  {
    name: "Veera",
    type: "Dog",
    breed: "Rajapalayam",
    age: "4 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/561eb63e-3fac-471e-ad3f-f696ffff1cec.png",
    personality: ["Majestic", "Loyal", "Guard Dog"],
    description: "Veera is a magnificent Rajapalayam, an ancient Indian breed. He's fiercely loyal, excellent as a guard dog, and has a noble temperament.",
    weight: "30 kg",
    color: "White",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 2000,
    shelterIndex: 1,
  },
  {
    name: "Golu",
    type: "Dog",
    breed: "Pomeranian",
    age: "2 years",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/e6185787-0a71-47a3-bf40-ea0b7604a373.png",
    personality: ["Adorable", "Fluffy", "Apartment Friendly"],
    description: "Golu is a tiny ball of fluff! This Pomeranian loves being the center of attention, enjoys lap time, and is perfect for apartment living.",
    weight: "3 kg",
    color: "Orange",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 4000,
    shelterIndex: 4,
  },
  {
    name: "Arjun",
    type: "Dog",
    breed: "Mudhol Hound",
    age: "3 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/a8f0ff46-cf30-46a1-87eb-53e472d75fda.png",
    personality: ["Athletic", "Independent", "Swift"],
    description: "Arjun is a graceful Mudhol Hound, a proud Indian breed. He's incredibly fast, loves open spaces, and is perfect for an active family.",
    weight: "22 kg",
    color: "Fawn",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 1500,
    shelterIndex: 2,
  },
  {
    name: "Snowbell",
    type: "Cat",
    breed: "Persian",
    age: "2 years",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/8d664a14-a1a9-4811-9d85-bc8d3e518c53.png",
    personality: ["Calm", "Elegant", "Indoor"],
    description: "Snowbell is a gorgeous white Persian cat with stunning blue eyes. She loves lounging on soft cushions and being gently brushed.",
    weight: "4 kg",
    color: "White",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 5000,
    shelterIndex: 0,
  },
  {
    name: "Marmalade",
    type: "Cat",
    breed: "Indian Domestic (Tabby)",
    age: "1 year",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/c48c3404-ac1c-4664-b485-5bc283d371a4.png",
    personality: ["Curious", "Affectionate", "Sunbather"],
    description: "Marmalade is a handsome orange tabby who loves basking in the sun. He's very affectionate, purrs loudly, and enjoys window watching.",
    weight: "4.5 kg",
    color: "Orange Tabby",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 1500,
    shelterIndex: 1,
  },
  {
    name: "Kali",
    type: "Cat",
    breed: "Bombay",
    age: "3 years",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/762fa48d-971d-454b-91e9-10119d3d4993.png",
    personality: ["Sleek", "Mysterious", "Playful at Night"],
    description: "Kali is a stunning black Bombay cat with mesmerizing golden eyes. She's independent during the day but loves midnight play sessions.",
    weight: "3.5 kg",
    color: "Black",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 2000,
    shelterIndex: 7,
  },
  {
    name: "Mithai",
    type: "Cat",
    breed: "Calico (Indian Domestic)",
    age: "6 months",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/7111120f-c95b-4e2d-a13b-238c3228a71c.png",
    personality: ["Playful", "Kitten Energy", "Social"],
    description: "Mithai is an adorable calico kitten with the most playful personality. She loves chasing yarn balls and will melt your heart!",
    weight: "1.5 kg",
    color: "Calico",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 1200,
    shelterIndex: 10,
  },
  {
    name: "Meera",
    type: "Cat",
    breed: "Siamese",
    age: "2 years",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/881c2a7e-4988-481e-afb0-ffc25f24ae6f.png",
    personality: ["Vocal", "Intelligent", "Loyal"],
    description: "Meera is a beautiful Siamese cat who loves to 'talk'. She's very intelligent, can learn tricks, and bonds deeply with her human.",
    weight: "3.8 kg",
    color: "Cream & Brown",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 4500,
    shelterIndex: 8,
  },
  {
    name: "Moti",
    type: "Cat",
    breed: "British Shorthair",
    age: "1.5 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/34b16536-736c-47dc-be0e-46b52899dec1.png",
    personality: ["Chunky", "Laid-back", "Quiet"],
    description: "Moti is a plush grey British Shorthair with the roundest face. He's the definition of a couch potato and loves quiet evenings.",
    weight: "5 kg",
    color: "Grey",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 6000,
    shelterIndex: 3,
  },
  {
    name: "Bunny",
    type: "Rabbit",
    breed: "Holland Lop",
    age: "8 months",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/63a52566-1f7f-4854-ab50-b44e64708387.png",
    personality: ["Gentle", "Floppy Ears", "Easy to Handle"],
    description: "Bunny is a sweet Holland Lop with the most adorable floppy ears. She's gentle, loves being held, and is great for first-time pet owners.",
    weight: "1.8 kg",
    color: "White",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 2000,
    shelterIndex: 11,
  },
  {
    name: "Caramel",
    type: "Rabbit",
    breed: "Rex Rabbit",
    age: "1 year",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/51022620-f77d-4311-bfad-e9bc8d2bc8d8.png",
    personality: ["Soft Fur", "Active", "Friendly"],
    description: "Caramel has the softest velvety fur you'll ever touch! This Rex rabbit is active, loves hopping around, and enjoys fresh veggies.",
    weight: "2.5 kg",
    color: "Brown",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 1800,
    shelterIndex: 5,
  },
  {
    name: "Mitthu",
    type: "Bird",
    breed: "Indian Ringneck Parakeet",
    age: "1 year",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/a4869828-a08c-4b99-a22f-401c11253407.png",
    personality: ["Talkative", "Colorful", "Smart"],
    description: "Mitthu is a vibrant green Indian Ringneck who can mimic words! He's incredibly smart, loves fruits, and will brighten up any home.",
    weight: "0.13 kg",
    color: "Green",
    vaccinated: false,
    neutered: false,
    isAdopted: false,
    adoptionFee: 3000,
    shelterIndex: 4,
  },
  {
    name: "Sunny",
    type: "Bird",
    breed: "Budgerigar",
    age: "6 months",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/d5aa11cf-6a77-4f46-8799-e90bab83ccb1.png",
    personality: ["Cheerful", "Social", "Low Maintenance"],
    description: "Sunny is a bright yellow budgie who loves to chirp and sing. She's social, enjoys company, and is perfect for beginners.",
    weight: "0.03 kg",
    color: "Yellow",
    vaccinated: false,
    neutered: false,
    isAdopted: false,
    adoptionFee: 800,
    shelterIndex: 14,
  },
  {
    name: "Hammy",
    type: "Hamster",
    breed: "Syrian Hamster",
    age: "4 months",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/8aeaca1e-10f5-42b9-9f48-bfa32d6c5693.png",
    personality: ["Adorable", "Nocturnal", "Cheek Stuffer"],
    description: "Hammy is the cutest Syrian hamster with chubby cheeks! He loves running on his wheel at night and stuffing his cheeks with sunflower seeds.",
    weight: "0.15 kg",
    color: "Golden",
    vaccinated: false,
    neutered: false,
    isAdopted: false,
    adoptionFee: 500,
    shelterIndex: 9,
  },
  {
    name: "Peanut",
    type: "Hamster",
    breed: "Roborovski Dwarf Hamster",
    age: "3 months",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/a0090ef0-7933-48e2-acbf-8d10cb8be5f4.png",
    personality: ["Tiny", "Fast", "Entertaining"],
    description: "Peanut is the tiniest and fastest hamster you'll meet! This Roborovski dwarf hamster is endlessly entertaining to watch.",
    weight: "0.025 kg",
    color: "Sandy",
    vaccinated: false,
    neutered: false,
    isAdopted: false,
    adoptionFee: 600,
    shelterIndex: 9,
  },
  {
    name: "Guddu",
    type: "Dog",
    breed: "Pug",
    age: "1 year",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/cc9b8360-ff17-4f36-8c05-ac05c4f51adb.png",
    personality: ["Wrinkly", "Couch Lover", "Snorer"],
    description: "Guddu is an irresistible Pug with the cutest wrinkly face. He loves napping, snoring, and following you around the house.",
    weight: "7 kg",
    color: "Fawn",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 4000,
    shelterIndex: 0,
  },
  {
    name: "Himalaya",
    type: "Cat",
    breed: "Himalayan",
    age: "3 years",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/44c0e031-9900-4201-a81c-c1b96260a320.png",
    personality: ["Regal", "Fluffy", "Gentle"],
    description: "Himalaya is a stunning Himalayan cat with piercing blue eyes and luxurious fur. She's gentle, loves grooming sessions, and is very regal.",
    weight: "4.2 kg",
    color: "Cream & Brown",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 7000,
    shelterIndex: 11,
  },
  {
    name: "Cheetah",
    type: "Dog",
    breed: "Chippiparai",
    age: "2 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/fdbbbb86-4b57-4e05-bdc6-d1c77ad63962.png",
    personality: ["Sleek", "Fast Runner", "One-Person Dog"],
    description: "Cheetah is a magnificent Chippiparai, a rare Indian sighthound. He's incredibly fast, sleek, and bonds deeply with one person.",
    weight: "20 kg",
    color: "Grey",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 1500,
    shelterIndex: 1,
  },
  {
    name: "Oreo",
    type: "Dog",
    breed: "Indian Pariah (Indie)",
    age: "5 months",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/f316eca2-0232-47cc-bb00-34510fcaeced.png",
    personality: ["Puppy Energy", "Patches", "Loves Belly Rubs"],
    description: "Oreo is the cutest black and white Indie puppy! She's full of energy, loves belly rubs, and will be your most loyal companion.",
    weight: "6 kg",
    color: "Black & White",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 800,
    shelterIndex: 12,
  },
  {
    name: "Tota",
    type: "Bird",
    breed: "Cockatiel",
    age: "1 year",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/d7191d52-6311-4f4e-9ba1-4e44f39a6be4.png",
    personality: ["Whistler", "Friendly", "Head Crest"],
    description: "Tota is a charming Cockatiel who loves to whistle tunes. He raises his crest when happy and enjoys sitting on your shoulder.",
    weight: "0.09 kg",
    color: "White & Orange",
    vaccinated: false,
    neutered: false,
    isAdopted: false,
    adoptionFee: 2500,
    shelterIndex: 13,
  },
  {
    name: "Tara",
    type: "Turtle",
    breed: "Indian Star Tortoise",
    age: "5 years",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/050382ff-003e-4526-a6d7-ec4fa3151d79.png",
    personality: ["Slow & Steady", "Beautiful Shell", "Long-lived"],
    description: "Tara is a beautiful Indian Star Tortoise with stunning star patterns on her shell. She's low maintenance and can be your companion for decades!",
    weight: "1.5 kg",
    color: "Black & Yellow Stars",
    vaccinated: false,
    neutered: false,
    isAdopted: false,
    adoptionFee: 3500,
    shelterIndex: 5,
  },
  {
    name: "Charlie",
    type: "Dog",
    breed: "Cocker Spaniel",
    age: "2 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/ebbd2002-8ba2-4e0a-a23c-e8260c7840ad.png",
    personality: ["Happy", "Wavy Coat", "Family Dog"],
    description: "Charlie is a gorgeous Cocker Spaniel with a golden wavy coat. He's always happy, loves family time, and is great with everyone.",
    weight: "12 kg",
    color: "Golden",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 3500,
    shelterIndex: 3,
  },
  {
    name: "Simba",
    type: "Cat",
    breed: "Maine Coon",
    age: "2 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/111ae7a3-7440-4eab-8aef-1d3c54596c5f.png",
    personality: ["Giant", "Gentle", "Dog-like"],
    description: "Simba is a majestic Maine Coon - the gentle giant of cats! He follows you around like a dog, loves water, and has the fluffiest tail.",
    weight: "7 kg",
    color: "Brown Tabby",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 8000,
    shelterIndex: 2,
  },
  {
    name: "Tashi",
    type: "Dog",
    breed: "Lhasa Apso",
    age: "4 years",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/9700de98-5db7-4f4d-8196-714681e717cb.png",
    personality: ["Long Coat", "Watchful", "Compact"],
    description: "Tashi is a beautiful Lhasa Apso with a flowing coat. Originally from Tibet, she's watchful, compact, and perfect for Indian homes.",
    weight: "6 kg",
    color: "Golden & White",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 3000,
    shelterIndex: 11,
  },
  {
    name: "Sausage",
    type: "Dog",
    breed: "Dachshund",
    age: "1 year",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/dab90eb8-a366-405a-a259-60b7461d9d0c.png",
    personality: ["Long Body", "Brave", "Funny"],
    description: "Sausage is a hilarious Dachshund with the longest body and shortest legs! He's surprisingly brave, loves to dig, and will make you laugh daily.",
    weight: "5 kg",
    color: "Brown",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 4500,
    shelterIndex: 8,
  },
  // 6 NEW PETS ADDED BELOW
  {
    name: "Luna",
    type: "Cat",
    breed: "Russian Blue",
    age: "1.5 years",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/8d664a14-a1a9-4811-9d85-bc8d3e518c53.png",
    personality: ["Graceful", "Shy at First", "Deeply Loyal"],
    description: "Luna is a stunning Russian Blue with a shimmering silver coat and emerald green eyes. She may be shy initially but once she trusts you, she becomes your shadow and most devoted companion.",
    weight: "3.5 kg",
    color: "Silver Blue",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 5500,
    shelterIndex: 6,
  },
  {
    name: "Rocky",
    type: "Dog",
    breed: "Rottweiler",
    age: "2.5 years",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/d47e9508-14d1-43de-a5c2-8ceffdd630b5.png",
    personality: ["Strong", "Gentle Giant", "Family Protector"],
    description: "Rocky is a powerful yet gentle Rottweiler who loves his family more than anything. Despite his imposing size, he's a big softie who loves belly rubs and playing with children.",
    weight: "45 kg",
    color: "Black & Mahogany",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 3500,
    shelterIndex: 9,
  },
  {
    name: "Nemo",
    type: "Fish",
    breed: "Clownfish",
    age: "1 year",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/050382ff-003e-4526-a6d7-ec4fa3151d79.png",
    personality: ["Colorful", "Active Swimmer", "Easy Care"],
    description: "Nemo is a vibrant orange and white clownfish who brings life to any aquarium. He's active, healthy, and perfect for both beginner and experienced fish keepers.",
    weight: "0.02 kg",
    color: "Orange & White",
    vaccinated: false,
    neutered: false,
    isAdopted: false,
    adoptionFee: 500,
    shelterIndex: 14,
  },
  {
    name: "Pepper",
    type: "Cat",
    breed: "Bengal",
    age: "1 year",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/762fa48d-971d-454b-91e9-10119d3d4993.png",
    personality: ["Wild Look", "Energetic", "Loves Water"],
    description: "Pepper is a striking Bengal cat with beautiful rosette markings that make him look like a mini leopard. He's incredibly energetic, loves playing in water, and needs an active household.",
    weight: "5.5 kg",
    color: "Brown Spotted",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 9000,
    shelterIndex: 7,
  },
  {
    name: "Daisy",
    type: "Dog",
    breed: "Golden Retriever",
    age: "1 year",
    gender: "Female",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/fa147b42-d724-47d2-b21c-53e5a25a72fd.png",
    personality: ["Sunshine", "Therapy Dog", "Loves Everyone"],
    description: "Daisy is a radiant Golden Retriever with the warmest personality. She has therapy dog potential, loves meeting new people, and her tail never stops wagging.",
    weight: "25 kg",
    color: "Golden",
    vaccinated: true,
    neutered: true,
    isAdopted: false,
    adoptionFee: 3000,
    shelterIndex: 10,
  },
  {
    name: "Cotton",
    type: "Rabbit",
    breed: "Angora Rabbit",
    age: "6 months",
    gender: "Male",
    image: "https://mgx-backend-cdn.metadl.com/generate/images/972017/2026-02-15/63a52566-1f7f-4854-ab50-b44e64708387.png",
    personality: ["Ultra Fluffy", "Calm", "Loves Grooming"],
    description: "Cotton is the fluffiest Angora rabbit you'll ever see! He looks like a living cloud and absolutely loves being groomed. He's calm, gentle, and perfect for a patient owner.",
    weight: "2.8 kg",
    color: "Pure White",
    vaccinated: true,
    neutered: false,
    isAdopted: false,
    adoptionFee: 2500,
    shelterIndex: 5,
  },
];

export async function POST() {
  try {
    await connectDB();

    // Clear existing data
    await Shelter.deleteMany({});
    await Pet.deleteMany({});

    // Insert shelters
    const createdShelters = await Shelter.insertMany(sheltersData);
    console.log(`Created ${createdShelters.length} shelters`);

    // Map pets to their shelters
    const petsWithShelters = petsData.map((pet) => {
      const shelterIdx = Math.min(pet.shelterIndex, createdShelters.length - 1);
      const shelter = createdShelters[shelterIdx];
      return {
        name: pet.name,
        type: pet.type,
        breed: pet.breed,
        age: pet.age,
        gender: pet.gender,
        image: pet.image,
        images: [pet.image],
        shelter: shelter._id,
        shelterName: `${shelter.name}, ${shelter.city}`,
        personality: pet.personality,
        description: pet.description,
        weight: pet.weight,
        color: pet.color,
        vaccinated: pet.vaccinated,
        neutered: pet.neutered,
        isAdopted: pet.isAdopted,
        adoptionFee: pet.adoptionFee,
      };
    });

    const createdPets = await Pet.insertMany(petsWithShelters);
    console.log(`Created ${createdPets.length} pets`);

    return NextResponse.json({
      success: true,
      message: `Database seeded successfully! Created ${createdShelters.length} shelters and ${createdPets.length} pets.`,
      data: {
        shelters: createdShelters.length,
        pets: createdPets.length,
      },
    });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json(
      { success: false, error: `Failed to seed database: ${error}` },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    message: "Send a POST request to /api/seed to seed the database with 15 Indian shelters and 36 pets.",
  });
}